# Generated by Django 4.0.1 on 2023-04-09 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.helper_methods


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=65, verbose_name='Title')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Uploaded'), (2, 'Deleted')], default=1, verbose_name='Status')),
                ('pin_file', models.FileField(upload_to=utils.helper_methods.update_pin_file_name, verbose_name='Pin')),
                ('about', models.CharField(max_length=250, verbose_name='About')),
                ('alter_text', models.TextField(blank=True, null=True, verbose_name='Alter Text')),
                ('destination_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Download from URL')),
                ('is_idea', models.BooleanField(default=False, verbose_name='Is Idea Pin')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Private Pin')),
                ('category', models.ManyToManyField(to='pinterest.Category', verbose_name='Categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Pin',
                'verbose_name_plural': 'Pins',
            },
        ),
    ]
