# Generated by Django 4.0.1 on 2023-04-12 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_account', '0003_alter_userprofile_about_alter_userprofile_country_and_more'),
        ('pinterest', '0002_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Saved Pin',
                'verbose_name_plural': 'Saved Pins',
            },
        ),
        migrations.AddField(
            model_name='pin',
            name='saved_pin',
            field=models.ManyToManyField(related_name='user_saved_pins', through='pinterest.SavedPin', to=settings.AUTH_USER_MODEL, verbose_name='Saved Pin'),
        ),
        migrations.AddField(
            model_name='savedpin',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pins', to='pinterest.pin', verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='savedpin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pins', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='savedpin',
            unique_together={('user', 'pin')},
        ),
    ]
