# Generated by Django 4.0.1 on 2023-04-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0005_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='board',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Is Private'),
        ),
    ]
