# Generated by Django 4.0.1 on 2023-04-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0006_board_is_active_board_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='is_active',
        ),
    ]
