# Generated by Django 4.0.1 on 2023-04-04 09:16

from django.db import migrations, models
import utils.helper_methods


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helper_methods.update_user_cover_picture_name, verbose_name='Cover Picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helper_methods.update_user_profile_picture_name, verbose_name='Profile Picture'),
        ),
    ]
